/**
 * COMPREHENSIVE RULE DEFINITIONS — Phase 3.1
 *
 * Every rule from sliderbed_v1/rules.ts registered with:
 * - Unique stable ID matching generateRuleId() output
 * - Human-readable name and description
 * - Category for grouping in audit panel
 * - Field, severity, and source function
 *
 * Total: 157 rules across 7 functions.
 *
 * Categories:
 * - geometry: Conveyor length, incline, geometry mode, horizontal run, TOB
 * - pulley: Pulley diameter, min pulley, drive/tail pulley
 * - speed: Belt speed, drive RPM, speed mode
 * - sprocket: Sprocket teeth, chain ratio (bottom mount)
 * - material: Material form, parts dimensions, bulk input, density, lump size
 * - belt: Belt selection, PIW/PIL, coefficients, overrides, V-guide, tracking
 * - shaft: Shaft diameter, manual mode
 * - cleat: Cleat height, spacing, edge offset, compatibility
 * - frame: Frame height, construction, custom height, low profile
 * - support: Floor support, legs, casters, TOB (commit), adjustment range
 * - safety: Finger safe, end guards, bottom covers, lacing
 * - application: Temperature, fluid, drop height, incline warnings, side load
 * - drive: Gear ratio, motor RPM, start/stop cycle
 * - return_support: Snub rollers, gravity rollers, end offset
 * - parameter: Friction coeff, safety factor, starting pull, gravity constant
 * - pci: Tube stress, hub connection, bushing system
 * - premium: Premium feature flags (belt only)
 * - height: Angle mismatch, adjustment range warnings
 */

export interface RuleDefinition {
  /** Stable identifier — matches field + condition for deterministic lookup */
  rule_id: string;
  /** Human-readable name for audit panel display */
  human_name: string;
  /** Plain-English description of what this rule checks */
  check_description: string;
  /** Category for grouping */
  category: RuleCategory;
  /** Primary input field examined */
  field: string;
  /** Default severity when fired */
  default_severity: 'error' | 'warning' | 'info';
  /** Source function in rules.ts */
  source_function: string;
  /** Approximate line number in rules.ts */
  source_line: number;
  /**
   * Optional unique static substring from the rule's fired message.
   * Used to disambiguate when field + severity isn't unique.
   * When absent, keyword overlap between check_description and message is used.
   */
  message_match?: string;
}

export type RuleCategory =
  | 'geometry'
  | 'pulley'
  | 'speed'
  | 'sprocket'
  | 'material'
  | 'belt'
  | 'shaft'
  | 'cleat'
  | 'frame'
  | 'support'
  | 'safety'
  | 'application'
  | 'drive'
  | 'return_support'
  | 'parameter'
  | 'pci'
  | 'premium'
  | 'height';

/** Human-readable category labels for the audit panel */
export const CATEGORY_LABELS: Record<RuleCategory, string> = {
  geometry: 'Geometry & Layout',
  pulley: 'Pulley Diameter',
  speed: 'Speed & RPM',
  sprocket: 'Sprocket & Chain',
  material: 'Material & Product',
  belt: 'Belt Selection & Tracking',
  shaft: 'Shaft Diameter',
  cleat: 'Cleats',
  frame: 'Frame & Construction',
  support: 'Floor Support & Hardware',
  safety: 'Safety & Features',
  application: 'Application & Environment',
  drive: 'Drive & Gearbox',
  return_support: 'Return Support',
  parameter: 'Calculation Parameters',
  pci: 'PCI Tube Stress & Hub',
  premium: 'Premium Features',
  height: 'Height & Angle',
};

/**
 * Complete rule definitions extracted from sliderbed_v1/rules.ts.
 *
 * Rules are ordered by source function and line number to match evaluation order.
 */
export const RULE_DEFINITIONS: RuleDefinition[] = [
  // =========================================================================
  // validateInputs() — Input validation errors
  // =========================================================================

  // --- Geometry & Layout ---
  {
    rule_id: 'vi_conveyor_length_zero',
    human_name: 'Conveyor Length Required',
    check_description: 'Conveyor center-to-center length must be greater than 0',
    category: 'geometry',
    field: 'conveyor_length_cc_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 153,
  },
  {
    rule_id: 'vi_belt_width_zero',
    human_name: 'Belt Width Required',
    check_description: 'Belt width must be greater than 0',
    category: 'geometry',
    field: 'belt_width_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 161,
  },
  {
    rule_id: 'vi_incline_negative',
    human_name: 'Negative Incline',
    check_description: 'Incline angle must be >= 0 degrees',
    category: 'geometry',
    field: 'conveyor_incline_deg',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 169,
  },
  {
    rule_id: 'vi_horizontal_run_zero',
    human_name: 'Horizontal Run Required',
    check_description: 'Horizontal run must be > 0 when using H_ANGLE or H_TOB geometry mode',
    category: 'geometry',
    field: 'horizontal_run_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 185,
  },
  {
    rule_id: 'vi_tail_tob_required_htob',
    human_name: 'Tail TOB Required (H_TOB Mode)',
    check_description: 'Tail TOB is required in Horizontal + TOBs geometry mode',
    category: 'geometry',
    field: 'tail_tob_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 197,
  },
  {
    rule_id: 'vi_drive_tob_required_htob',
    human_name: 'Drive TOB Required (H_TOB Mode)',
    check_description: 'Drive TOB is required in Horizontal + TOBs geometry mode',
    category: 'geometry',
    field: 'drive_tob_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 204,
  },

  // --- Pulley Diameter ---
  {
    rule_id: 'vi_pulley_diameter_zero',
    human_name: 'Pulley Diameter Required',
    check_description: 'Pulley diameter must be greater than 0',
    category: 'pulley',
    field: 'pulley_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 212,
  },
  {
    rule_id: 'vi_drive_pulley_zero',
    human_name: 'Drive Pulley Zero',
    check_description: 'Drive pulley diameter must be greater than 0',
    category: 'pulley',
    field: 'drive_pulley_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 222,
  },
  {
    rule_id: 'vi_drive_pulley_min',
    human_name: 'Drive Pulley Below Minimum',
    check_description: 'Drive pulley diameter must be >= 2.5"',
    category: 'pulley',
    field: 'drive_pulley_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 229,
  },
  {
    rule_id: 'vi_tail_pulley_zero',
    human_name: 'Tail Pulley Zero',
    check_description: 'Tail pulley diameter must be greater than 0',
    category: 'pulley',
    field: 'tail_pulley_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 241,
  },
  {
    rule_id: 'vi_tail_pulley_min',
    human_name: 'Tail Pulley Below Minimum',
    check_description: 'Tail pulley diameter must be >= 2.5"',
    category: 'pulley',
    field: 'tail_pulley_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 248,
  },

  // --- Speed Mode ---
  {
    rule_id: 'vi_belt_speed_zero',
    human_name: 'Belt Speed Required',
    check_description: 'Belt speed (FPM) must be > 0 when in Belt Speed mode',
    category: 'speed',
    field: 'belt_speed_fpm',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 270,
  },
  {
    rule_id: 'vi_drive_rpm_zero',
    human_name: 'Drive RPM Required',
    check_description: 'Drive RPM must be > 0 when in Drive RPM mode',
    category: 'speed',
    field: 'drive_rpm_input',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 281,
  },
  {
    rule_id: 'vi_pulley_dia_for_speed',
    human_name: 'Pulley Diameter for Speed Calc',
    check_description: 'Drive pulley diameter must be > 0 for speed calculations',
    category: 'speed',
    field: 'drive_pulley_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 291,
  },

  // --- Sprocket (Bottom Mount) ---
  {
    rule_id: 'vi_gm_sprocket_teeth_zero',
    human_name: 'GM Sprocket Teeth Required',
    check_description: 'Gearmotor sprocket teeth must be > 0 when bottom-mounted',
    category: 'sprocket',
    field: 'gm_sprocket_teeth',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 308,
  },
  {
    rule_id: 'vi_gm_sprocket_teeth_integer',
    human_name: 'GM Sprocket Teeth Must Be Integer',
    check_description: 'Sprocket teeth must be a whole number',
    category: 'sprocket',
    field: 'gm_sprocket_teeth',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 314,
  },
  {
    rule_id: 'vi_drive_shaft_sprocket_zero',
    human_name: 'Drive Shaft Sprocket Required',
    check_description: 'Drive shaft sprocket teeth must be > 0 when bottom-mounted',
    category: 'sprocket',
    field: 'drive_shaft_sprocket_teeth',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 323,
  },
  {
    rule_id: 'vi_drive_shaft_sprocket_integer',
    human_name: 'Drive Shaft Sprocket Must Be Integer',
    check_description: 'Sprocket teeth must be a whole number',
    category: 'sprocket',
    field: 'drive_shaft_sprocket_teeth',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 329,
  },

  // --- Throughput ---
  {
    rule_id: 'vi_throughput_negative',
    human_name: 'Throughput Negative',
    check_description: 'Required throughput must be >= 0',
    category: 'material',
    field: 'required_throughput_pph',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 348,
  },
  {
    rule_id: 'vi_throughput_margin_negative',
    human_name: 'Throughput Margin Negative',
    check_description: 'Throughput margin must be >= 0',
    category: 'material',
    field: 'throughput_margin_pct',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 357,
  },

  // --- Material Form ---
  {
    rule_id: 'vi_material_form_required',
    human_name: 'Material Form Required',
    check_description: 'Material form (PARTS or BULK) must be selected before calculation',
    category: 'material',
    field: 'material_form',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 377,
  },

  // --- Parts Mode ---
  {
    rule_id: 'vi_part_weight_required',
    human_name: 'Part Weight Required',
    check_description: 'Part weight must be > 0 in PARTS mode',
    category: 'material',
    field: 'part_weight_lbs',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 397,
  },
  {
    rule_id: 'vi_part_length_required',
    human_name: 'Part Length Required',
    check_description: 'Part length must be > 0 in PARTS mode',
    category: 'material',
    field: 'part_length_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 406,
  },
  {
    rule_id: 'vi_part_width_required',
    human_name: 'Part Width Required',
    check_description: 'Part width must be > 0 in PARTS mode',
    category: 'material',
    field: 'part_width_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 415,
  },

  // --- Bulk Mode ---
  {
    rule_id: 'vi_bulk_method_required',
    human_name: 'Bulk Input Method Required',
    check_description: 'Bulk input method must be selected in BULK mode',
    category: 'material',
    field: 'bulk_input_method',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 436,
  },
  {
    rule_id: 'vi_mass_flow_required',
    human_name: 'Mass Flow Rate Required',
    check_description: 'Mass flow rate must be > 0 in Weight Flow mode',
    category: 'material',
    field: 'mass_flow_lbs_per_hr',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 446,
  },
  {
    rule_id: 'vi_volume_flow_required',
    human_name: 'Volume Flow Rate Required',
    check_description: 'Volume flow rate must be > 0 in Volume Flow mode',
    category: 'material',
    field: 'volume_flow_ft3_per_hr',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 457,
  },
  {
    rule_id: 'vi_density_required',
    human_name: 'Material Density Required',
    check_description: 'Material density must be > 0 in Volume Flow mode',
    category: 'material',
    field: 'density_lbs_per_ft3',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 465,
  },
  {
    rule_id: 'vi_density_source_required',
    human_name: 'Density Source Required',
    check_description: 'Density source must be specified in Volume Flow mode',
    category: 'material',
    field: 'density_source',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 473,
  },

  // --- Part Spacing ---
  {
    rule_id: 'vi_part_spacing_negative',
    human_name: 'Part Spacing Negative',
    check_description: 'Part spacing must be >= 0 in PARTS mode',
    category: 'material',
    field: 'part_spacing_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 488,
  },

  // --- Drop Height ---
  {
    rule_id: 'vi_drop_height_negative',
    human_name: 'Drop Height Negative',
    check_description: 'Drop height cannot be negative',
    category: 'application',
    field: 'drop_height_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 497,
  },

  // --- Power-User Parameters ---
  {
    rule_id: 'vi_safety_factor_low',
    human_name: 'Safety Factor Too Low',
    check_description: 'Safety factor must be >= 1.0',
    category: 'parameter',
    field: 'safety_factor',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 506,
  },
  {
    rule_id: 'vi_safety_factor_high',
    human_name: 'Safety Factor Too High',
    check_description: 'Safety factor must be <= 5.0',
    category: 'parameter',
    field: 'safety_factor',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 514,
  },
  {
    rule_id: 'vi_piw_zero',
    human_name: 'PIW Must Be Positive',
    check_description: 'Belt weight coefficient PIW must be > 0',
    category: 'belt',
    field: 'belt_coeff_piw',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 522,
  },
  {
    rule_id: 'vi_piw_range',
    human_name: 'PIW Out of Range',
    check_description: 'PIW should be between 0.05 and 0.30 lb/in',
    category: 'belt',
    field: 'belt_coeff_piw',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 530,
  },
  {
    rule_id: 'vi_pil_zero',
    human_name: 'PIL Must Be Positive',
    check_description: 'Belt weight coefficient PIL must be > 0',
    category: 'belt',
    field: 'belt_coeff_pil',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 538,
  },
  {
    rule_id: 'vi_pil_range',
    human_name: 'PIL Out of Range',
    check_description: 'PIL should be between 0.05 and 0.30 lb/in',
    category: 'belt',
    field: 'belt_coeff_pil',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 546,
  },
  {
    rule_id: 'vi_starting_pull_negative',
    human_name: 'Starting Pull Negative',
    check_description: 'Starting belt pull must be >= 0',
    category: 'parameter',
    field: 'starting_belt_pull_lb',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 554,
  },
  {
    rule_id: 'vi_starting_pull_high',
    human_name: 'Starting Pull Too High',
    check_description: 'Starting belt pull must be <= 2000 lb',
    category: 'parameter',
    field: 'starting_belt_pull_lb',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 562,
  },
  {
    rule_id: 'vi_friction_coeff_low',
    human_name: 'Friction Coefficient Too Low',
    check_description: 'Friction coefficient must be >= 0.05',
    category: 'parameter',
    field: 'friction_coeff',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 570,
  },
  {
    rule_id: 'vi_friction_coeff_high',
    human_name: 'Friction Coefficient Too High',
    check_description: 'Friction coefficient must be <= 0.6',
    category: 'parameter',
    field: 'friction_coeff',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 578,
  },
  {
    rule_id: 'vi_motor_rpm_low',
    human_name: 'Motor RPM Too Low',
    check_description: 'Motor RPM must be >= 800',
    category: 'drive',
    field: 'motor_rpm',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 586,
  },
  {
    rule_id: 'vi_motor_rpm_high',
    human_name: 'Motor RPM Too High',
    check_description: 'Motor RPM must be <= 3600',
    category: 'drive',
    field: 'motor_rpm',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 594,
  },

  // --- Belt Tracking & V-Guide ---
  {
    rule_id: 'vi_vguide_profile_required',
    human_name: 'V-Guide Profile Required',
    check_description: 'V-guide profile is required when tracking method is V-guided',
    category: 'belt',
    field: 'v_guide_key',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 608,
  },
  {
    rule_id: 'vi_pu_belt_vguide_incompatible',
    human_name: 'PU Belt + V-Guide Incompatible',
    check_description: 'Selected V-guide does not support PU belts (missing PU pulley data)',
    category: 'belt',
    field: 'v_guide_key',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 620,
  },

  // --- Shaft Diameter ---
  {
    rule_id: 'vi_drive_shaft_manual_required',
    human_name: 'Drive Shaft Diameter Required (Manual)',
    check_description: 'Drive shaft diameter is required when shaft mode is Manual',
    category: 'shaft',
    field: 'drive_shaft_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 635,
  },
  {
    rule_id: 'vi_tail_shaft_manual_required',
    human_name: 'Tail Shaft Diameter Required (Manual)',
    check_description: 'Tail shaft diameter is required when shaft mode is Manual',
    category: 'shaft',
    field: 'tail_shaft_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 642,
  },

  // --- Belt Override ---
  {
    rule_id: 'vi_piw_override_zero',
    human_name: 'PIW Override Must Be Positive',
    check_description: 'Belt PIW override must be > 0',
    category: 'belt',
    field: 'belt_piw_override',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 652,
  },
  {
    rule_id: 'vi_piw_override_range',
    human_name: 'PIW Override Out of Range',
    check_description: 'Belt PIW override should be between 0.05 and 0.30 lb/in',
    category: 'belt',
    field: 'belt_piw_override',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 660,
  },
  {
    rule_id: 'vi_pil_override_zero',
    human_name: 'PIL Override Must Be Positive',
    check_description: 'Belt PIL override must be > 0',
    category: 'belt',
    field: 'belt_pil_override',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 668,
  },
  {
    rule_id: 'vi_pil_override_range',
    human_name: 'PIL Override Out of Range',
    check_description: 'Belt PIL override should be between 0.05 and 0.30 lb/in',
    category: 'belt',
    field: 'belt_pil_override',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 676,
  },

  // --- Belt Selection ---
  {
    rule_id: 'vi_belt_selection_required',
    human_name: 'Belt Selection Required',
    check_description: 'A belt must be selected from catalog or coefficients provided',
    category: 'belt',
    field: 'belt_catalog_key',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 699,
  },

  // --- Shaft Range ---
  {
    rule_id: 'vi_drive_shaft_min',
    human_name: 'Drive Shaft Too Small',
    check_description: 'Drive shaft diameter must be >= 0.5"',
    category: 'shaft',
    field: 'drive_shaft_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 710,
  },
  {
    rule_id: 'vi_drive_shaft_max',
    human_name: 'Drive Shaft Too Large',
    check_description: 'Drive shaft diameter must be <= 4.0"',
    category: 'shaft',
    field: 'drive_shaft_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 717,
  },
  {
    rule_id: 'vi_tail_shaft_min',
    human_name: 'Tail Shaft Too Small',
    check_description: 'Tail shaft diameter must be >= 0.5"',
    category: 'shaft',
    field: 'tail_shaft_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 727,
  },
  {
    rule_id: 'vi_tail_shaft_max',
    human_name: 'Tail Shaft Too Large',
    check_description: 'Tail shaft diameter must be <= 4.0"',
    category: 'shaft',
    field: 'tail_shaft_diameter_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 734,
  },

  // --- Cleats ---
  {
    rule_id: 'vi_cleat_height_required',
    human_name: 'Cleat Height Required',
    check_description: 'Cleat height is required when cleats are enabled',
    category: 'cleat',
    field: 'cleat_height_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 753,
  },
  {
    rule_id: 'vi_cleat_height_min',
    human_name: 'Cleat Height Too Small',
    check_description: 'Cleat height must be >= 0.5"',
    category: 'cleat',
    field: 'cleat_height_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 763,
  },
  {
    rule_id: 'vi_cleat_height_max',
    human_name: 'Cleat Height Too Large',
    check_description: 'Cleat height must be <= 6"',
    category: 'cleat',
    field: 'cleat_height_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 770,
  },
  {
    rule_id: 'vi_cleat_spacing_required',
    human_name: 'Cleat Spacing Required',
    check_description: 'Cleat spacing is required when cleats are enabled',
    category: 'cleat',
    field: 'cleat_spacing_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 780,
  },
  {
    rule_id: 'vi_cleat_spacing_min',
    human_name: 'Cleat Spacing Too Small',
    check_description: 'Cleat spacing must be >= 2"',
    category: 'cleat',
    field: 'cleat_spacing_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 790,
  },
  {
    rule_id: 'vi_cleat_spacing_max',
    human_name: 'Cleat Spacing Too Large',
    check_description: 'Cleat spacing must be <= 48"',
    category: 'cleat',
    field: 'cleat_spacing_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 798,
  },
  {
    rule_id: 'vi_cleat_edge_offset_required',
    human_name: 'Cleat Edge Offset Required',
    check_description: 'Cleat edge offset is required when cleats are enabled',
    category: 'cleat',
    field: 'cleat_edge_offset_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 807,
  },
  {
    rule_id: 'vi_cleat_edge_offset_min',
    human_name: 'Cleat Edge Offset Negative',
    check_description: 'Cleat edge offset must be >= 0"',
    category: 'cleat',
    field: 'cleat_edge_offset_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 817,
  },
  {
    rule_id: 'vi_cleat_edge_offset_max',
    human_name: 'Cleat Edge Offset Too Large',
    check_description: 'Cleat edge offset must be <= 12"',
    category: 'cleat',
    field: 'cleat_edge_offset_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 825,
  },

  // --- TOB Values ---
  {
    rule_id: 'vi_tail_tob_negative',
    human_name: 'Tail TOB Negative',
    check_description: 'Tail TOB must be >= 0"',
    category: 'support',
    field: 'tail_tob_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 838,
  },
  {
    rule_id: 'vi_drive_tob_negative',
    human_name: 'Drive TOB Negative',
    check_description: 'Drive TOB must be >= 0"',
    category: 'support',
    field: 'drive_tob_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 846,
  },
  {
    rule_id: 'vi_adjustment_range_negative',
    human_name: 'Adjustment Range Negative',
    check_description: 'Adjustment range must be >= 0"',
    category: 'support',
    field: 'adjustment_required_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 854,
  },

  // --- Floor Support ---
  {
    rule_id: 'vi_tob_required_floor',
    human_name: 'TOB Required (Floor Supported)',
    check_description: 'Top of Belt height is required when conveyor is floor supported',
    category: 'support',
    field: 'tail_tob_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 876,
  },
  {
    rule_id: 'vi_leg_model_required',
    human_name: 'Leg Model Required',
    check_description: 'Leg model selection is required when legs are included',
    category: 'support',
    field: 'leg_model_key',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 887,
  },
  {
    rule_id: 'vi_caster_qty_zero',
    human_name: 'At Least One Caster Required',
    check_description: 'At least one caster (rigid or swivel) is required when casters are included',
    category: 'support',
    field: 'caster_rigid_qty',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 903,
  },
  {
    rule_id: 'vi_rigid_caster_model_required',
    human_name: 'Rigid Caster Model Required',
    check_description: 'Rigid caster model is required when rigid quantity > 0',
    category: 'support',
    field: 'caster_rigid_model_key',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 912,
  },
  {
    rule_id: 'vi_swivel_caster_model_required',
    human_name: 'Swivel Caster Model Required',
    check_description: 'Swivel caster model is required when swivel quantity > 0',
    category: 'support',
    field: 'caster_swivel_model_key',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 920,
  },
  {
    rule_id: 'vi_leg_model_legacy',
    human_name: 'Leg Model Required (Legacy)',
    check_description: 'Leg model selection is required when using floor-standing legs',
    category: 'support',
    field: 'leg_model_key',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 937,
  },
  {
    rule_id: 'vi_caster_qty_legacy',
    human_name: 'Caster Required (Legacy)',
    check_description: 'At least one caster is required when using casters (legacy support method)',
    category: 'support',
    field: 'caster_rigid_qty',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 950,
  },
  {
    rule_id: 'vi_rigid_caster_model_legacy',
    human_name: 'Rigid Caster Model (Legacy)',
    check_description: 'Rigid caster model required when rigid qty > 0 (legacy)',
    category: 'support',
    field: 'caster_rigid_model_key',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 960,
  },
  {
    rule_id: 'vi_swivel_caster_model_legacy',
    human_name: 'Swivel Caster Model (Legacy)',
    check_description: 'Swivel caster model required when swivel qty > 0 (legacy)',
    category: 'support',
    field: 'caster_swivel_model_key',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 967,
  },

  // --- Frame Height ---
  {
    rule_id: 'vi_custom_frame_height_required',
    human_name: 'Custom Frame Height Required',
    check_description: 'Custom frame height is required when frame mode is Custom',
    category: 'frame',
    field: 'custom_frame_height_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 984,
  },
  {
    rule_id: 'vi_custom_frame_height_min',
    human_name: 'Custom Frame Height Below Minimum',
    check_description: 'Custom frame height must meet minimum requirement',
    category: 'frame',
    field: 'custom_frame_height_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 990,
  },
  {
    rule_id: 'vi_custom_frame_height_zero',
    human_name: 'Custom Frame Height Zero',
    check_description: 'Custom frame height must be > 0"',
    category: 'frame',
    field: 'custom_frame_height_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 1001,
  },

  // --- Frame Construction ---
  {
    rule_id: 'vi_sheet_metal_gauge_required',
    human_name: 'Sheet Metal Gauge Required',
    check_description: 'Sheet metal gauge is required when frame construction is Sheet Metal',
    category: 'frame',
    field: 'frame_sheet_metal_gauge',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 1020,
  },
  {
    rule_id: 'vi_channel_series_required',
    human_name: 'Channel Series Required',
    check_description: 'Channel series is required when frame construction is Structural Channel',
    category: 'frame',
    field: 'frame_structural_channel_series',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 1031,
  },
  {
    rule_id: 'vi_pulley_end_frame_min',
    human_name: 'Pulley-to-Frame Distance Negative',
    check_description: 'Pulley end to frame inside distance must be >= 0"',
    category: 'frame',
    field: 'pulley_end_to_frame_inside_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 1042,
  },
  {
    rule_id: 'vi_pulley_end_frame_max',
    human_name: 'Pulley-to-Frame Distance Too Large',
    check_description: 'Pulley end to frame inside distance must be <= 6"',
    category: 'frame',
    field: 'pulley_end_to_frame_inside_in',
    default_severity: 'error',
    source_function: 'validateInputs',
    source_line: 1049,
  },

  // =========================================================================
  // validateParameters() — Parameter validation errors
  // =========================================================================
  {
    rule_id: 'vp_friction_coeff_range',
    human_name: 'Parameter: Friction Coefficient Range',
    check_description: 'Friction coefficient must be between 0.1 and 1.0',
    category: 'parameter',
    field: 'friction_coeff',
    default_severity: 'error',
    source_function: 'validateParameters',
    source_line: 1068,
  },
  {
    rule_id: 'vp_safety_factor_min',
    human_name: 'Parameter: Safety Factor Minimum',
    check_description: 'Safety factor must be >= 1.0',
    category: 'parameter',
    field: 'safety_factor',
    default_severity: 'error',
    source_function: 'validateParameters',
    source_line: 1076,
  },
  {
    rule_id: 'vp_starting_pull_min',
    human_name: 'Parameter: Starting Pull Minimum',
    check_description: 'Starting belt pull must be >= 0',
    category: 'parameter',
    field: 'starting_belt_pull_lb',
    default_severity: 'error',
    source_function: 'validateParameters',
    source_line: 1084,
  },
  {
    rule_id: 'vp_motor_rpm_zero',
    human_name: 'Parameter: Motor RPM Zero',
    check_description: 'Motor RPM must be > 0',
    category: 'parameter',
    field: 'motor_rpm',
    default_severity: 'error',
    source_function: 'validateParameters',
    source_line: 1092,
  },
  {
    rule_id: 'vp_gravity_zero',
    human_name: 'Parameter: Gravity Constant Zero',
    check_description: 'Gravity constant must be > 0',
    category: 'parameter',
    field: 'gravity_in_per_s2',
    default_severity: 'error',
    source_function: 'validateParameters',
    source_line: 1100,
  },

  // =========================================================================
  // applyApplicationRules() — Application warnings and errors
  // =========================================================================

  // --- Temperature & Fluid ---
  {
    rule_id: 'ar_red_hot_parts',
    human_name: 'Red Hot Parts Blocked',
    check_description: 'Red hot parts are not compatible with belt/sliderbed conveyors',
    category: 'application',
    field: 'part_temperature_class',
    default_severity: 'error',
    source_function: 'applyApplicationRules',
    source_line: 1130,
  },
  {
    rule_id: 'ar_considerable_oil',
    human_name: 'Considerable Oil/Liquid',
    check_description: 'Consider ribbed or specialty belt for considerable oil/liquid',
    category: 'application',
    field: 'fluid_type',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1139,
  },
  {
    rule_id: 'ar_long_conveyor',
    human_name: 'Long Conveyor',
    check_description: 'Conveyor length exceeds 120" (10 ft) — consider multi-section body',
    category: 'application',
    field: 'conveyor_length_cc_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1148,
  },
  {
    rule_id: 'ar_hot_parts',
    human_name: 'Hot Parts',
    check_description: 'Hot parts — consider high-temperature belt',
    category: 'application',
    field: 'part_temperature_class',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1157,
  },
  {
    rule_id: 'ar_minimal_oil',
    human_name: 'Minimal Residual Oil',
    check_description: 'Minimal residual oil present — informational note',
    category: 'application',
    field: 'fluid_type',
    default_severity: 'info',
    source_function: 'applyApplicationRules',
    source_line: 1166,
  },
  {
    rule_id: 'ar_drop_height_high',
    human_name: 'High Drop Height',
    check_description: 'Drop height >= 24" — consider impact or wear protection',
    category: 'application',
    field: 'drop_height_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1175,
  },

  // --- Incline ---
  {
    rule_id: 'ar_incline_over_45',
    human_name: 'Incline Exceeds 45°',
    check_description: 'Incline > 45° is not supported without positive engagement',
    category: 'application',
    field: 'conveyor_incline_deg',
    default_severity: 'error',
    source_function: 'applyApplicationRules',
    source_line: 1187,
  },
  {
    rule_id: 'ar_incline_35_45',
    human_name: 'Incline 35°–45° Warning',
    check_description: 'Incline > 35° — product retention by friction alone is unlikely; cleats or positive engagement required',
    category: 'application',
    field: 'conveyor_incline_deg',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1196,
  },
  {
    rule_id: 'ar_incline_20_35',
    human_name: 'Incline 20°–35° Warning',
    check_description: 'Incline > 20° — cleats or retention features typically required',
    category: 'application',
    field: 'conveyor_incline_deg',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1205,
  },

  // --- Bulk Mode Warnings ---
  {
    rule_id: 'ar_density_assumed',
    human_name: 'Density Assumed from Class',
    check_description: 'Material density assumed from class — verify for accuracy',
    category: 'material',
    field: 'density_lbs_per_ft3',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1222,
  },
  {
    rule_id: 'ar_smallest_lump_negative',
    human_name: 'Smallest Lump Size Negative',
    check_description: 'Smallest lump size must be >= 0',
    category: 'material',
    field: 'smallest_lump_size_in',
    default_severity: 'error',
    source_function: 'applyApplicationRules',
    source_line: 1234,
  },
  {
    rule_id: 'ar_largest_lump_negative',
    human_name: 'Largest Lump Size Negative',
    check_description: 'Largest lump size must be >= 0',
    category: 'material',
    field: 'largest_lump_size_in',
    default_severity: 'error',
    source_function: 'applyApplicationRules',
    source_line: 1242,
  },
  {
    rule_id: 'ar_lump_size_inversion',
    human_name: 'Lump Size Inversion',
    check_description: 'Smallest lump size cannot exceed largest lump size',
    category: 'material',
    field: 'smallest_lump_size_in',
    default_severity: 'error',
    source_function: 'applyApplicationRules',
    source_line: 1250,
  },
  {
    rule_id: 'ar_lump_exceeds_belt_width',
    human_name: 'Lump Exceeds 80% Belt Width',
    check_description: 'Largest lump exceeds 80% of belt width — consider wider belt or screening',
    category: 'material',
    field: 'largest_lump_size_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1262,
  },
  {
    rule_id: 'ar_surge_multiplier_low',
    human_name: 'Surge Multiplier Too Low',
    check_description: 'Surge multiplier must be >= 1.0 (peak cannot be less than average)',
    category: 'material',
    field: 'surge_multiplier',
    default_severity: 'error',
    source_function: 'applyApplicationRules',
    source_line: 1280,
  },
  {
    rule_id: 'ar_surge_multiplier_missing',
    human_name: 'Surge Multiplier Not Specified',
    check_description: 'Surge feed selected but no multiplier — default 1.5x will be assumed',
    category: 'material',
    field: 'surge_multiplier',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1288,
  },
  {
    rule_id: 'ar_weight_flow_no_density',
    human_name: 'Weight Flow Missing Density',
    check_description: 'Bulk density not provided in Weight Flow mode — specify for accuracy',
    category: 'material',
    field: 'density_lbs_per_ft3',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1300,
  },

  // --- Belt & Pulley Warnings ---
  {
    rule_id: 'ar_fleece_vguide',
    human_name: 'FLEECE Belt + V-Guide',
    check_description: 'V-guide pulley rules not defined for FLEECE belt family',
    category: 'belt',
    field: 'v_guide_key',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1338,
  },
  {
    rule_id: 'ar_drive_pulley_below_belt_min',
    human_name: 'Drive Pulley Below Belt Minimum',
    check_description: 'Drive pulley diameter is below belt minimum for current tracking method',
    category: 'pulley',
    field: 'drive_pulley_diameter_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1351,
  },
  {
    rule_id: 'ar_tail_pulley_below_belt_min',
    human_name: 'Tail Pulley Below Belt Minimum',
    check_description: 'Tail pulley diameter is below belt minimum for current tracking method',
    category: 'pulley',
    field: 'tail_pulley_diameter_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1360,
  },

  // --- Cleat Warnings ---
  {
    rule_id: 'ar_cleat_spacing_vs_part',
    human_name: 'Cleat Spacing vs Part Size',
    check_description: 'Cleat spacing is less than part travel dimension — parts may not fit',
    category: 'cleat',
    field: 'cleat_spacing_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1386,
  },
  {
    rule_id: 'ar_cleat_edge_offset_overlap',
    human_name: 'Cleat Edge Offset Overlap',
    check_description: 'Cleat edge offset exceeds half belt width — cleats would overlap',
    category: 'cleat',
    field: 'cleat_edge_offset_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1397,
  },

  // --- Safety & Features ---
  {
    rule_id: 'ar_finger_safe_no_guards',
    human_name: 'Finger Safe Without End Guards',
    check_description: 'Finger safety may require end guards depending on layout',
    category: 'safety',
    field: 'end_guards',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1411,
  },
  {
    rule_id: 'ar_finger_safe_no_covers',
    human_name: 'Finger Safe Without Bottom Covers',
    check_description: 'Bottom covers may be required to achieve finger-safe access underneath',
    category: 'safety',
    field: 'bottom_covers',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1420,
  },
  {
    rule_id: 'ar_clipper_lacing',
    human_name: 'Clipper Lacing Interference',
    check_description: 'Clipper lacing may interfere with end guards due to protrusion',
    category: 'safety',
    field: 'lacing_style',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1429,
  },

  // --- Belt Catalog Pulley Warnings (duplicate check with catalog key) ---
  {
    rule_id: 'ar_belt_catalog_drive_pulley_min',
    human_name: 'Belt Catalog: Drive Pulley Below Min',
    check_description: 'Drive pulley below belt catalog minimum — may cause belt damage',
    category: 'belt',
    field: 'drive_pulley_diameter_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1458,
  },
  {
    rule_id: 'ar_belt_catalog_tail_pulley_min',
    human_name: 'Belt Catalog: Tail Pulley Below Min',
    check_description: 'Tail pulley below belt catalog minimum — may cause belt damage',
    category: 'belt',
    field: 'tail_pulley_diameter_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1467,
  },

  // --- Application & Demand ---
  {
    rule_id: 'ar_start_stop_short_cycle',
    human_name: 'Start/Stop Short Cycle Time',
    check_description: 'Frequent start/stop (cycle < 10s) may require higher-duty gearbox',
    category: 'drive',
    field: 'cycle_time_seconds',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1486,
  },
  {
    rule_id: 'ar_heavy_sideload_no_vguide',
    human_name: 'Heavy Side Load Without V-Guide',
    check_description: 'Heavy side loading requires V-guided tracking — blocking error',
    category: 'application',
    field: 'belt_tracking_method',
    default_severity: 'error',
    source_function: 'applyApplicationRules',
    source_line: 1503,
  },
  {
    rule_id: 'ar_heavy_sideload_warning',
    human_name: 'Heavy Side Loading',
    check_description: 'Heavy side loading typically requires a V-guide for reliable tracking',
    category: 'application',
    field: 'side_loading_severity',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1509,
  },
  {
    rule_id: 'ar_moderate_sideload',
    human_name: 'Moderate Side Loading',
    check_description: 'Moderate side loading may require a V-guide for reliable tracking',
    category: 'application',
    field: 'side_loading_severity',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1515,
  },

  // --- Frame Height Warnings ---
  {
    rule_id: 'ar_frame_height_design_review',
    human_name: 'Low Frame Height — Design Review',
    check_description: 'Frame height is below design review threshold',
    category: 'frame',
    field: 'frame_height_mode',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1534,
  },
  {
    rule_id: 'ar_snub_rollers_required',
    human_name: 'Snub Rollers Required',
    check_description: 'Frame height is below snub roller threshold — snub rollers will be required',
    category: 'frame',
    field: 'frame_height_mode',
    default_severity: 'info',
    source_function: 'applyApplicationRules',
    source_line: 1548,
  },

  // --- Return Support ---
  {
    rule_id: 'ar_cleats_snub_interference',
    human_name: 'Cleats + Snub Rollers Interference',
    check_description: 'Cleats can interfere with snub wrap — verify clearance and snub diameter',
    category: 'return_support',
    field: 'return_snub_mode',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1584,
  },
  {
    rule_id: 'ar_low_profile_no_snubs',
    human_name: 'Low Profile Without Snub Rollers',
    check_description: 'Low Profile frame without snub rollers may cause belt sag at pulley ends',
    category: 'return_support',
    field: 'return_snub_mode',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1599,
  },
  {
    rule_id: 'ar_gravity_roller_sag',
    human_name: 'Gravity Roller Spacing Too Wide',
    check_description: 'Gravity roller spacing exceeds 72" — belt may sag between rollers',
    category: 'return_support',
    field: 'return_gravity_roller_count',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1608,
  },
  {
    rule_id: 'ar_gravity_roller_over_engineered',
    human_name: 'Gravity Rollers Over-Engineered',
    check_description: 'Gravity roller spacing less than 24" — may be over-engineered',
    category: 'return_support',
    field: 'return_gravity_roller_count',
    default_severity: 'info',
    source_function: 'applyApplicationRules',
    source_line: 1615,
  },
  {
    rule_id: 'ar_end_offset_too_small',
    human_name: 'End Offset Too Small',
    check_description: 'End offset less than 6" — rollers may be too close to pulley',
    category: 'return_support',
    field: 'return_end_offset_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1625,
  },
  {
    rule_id: 'ar_end_offset_too_large',
    human_name: 'End Offset Too Large',
    check_description: 'End offset exceeds 60" — excessive unsupported span near pulleys',
    category: 'return_support',
    field: 'return_end_offset_in',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1632,
  },

  // --- Frame Mode Info ---
  {
    rule_id: 'ar_low_profile_info',
    human_name: 'Low Profile Frame Selected',
    check_description: 'Low profile frame is a cost option',
    category: 'frame',
    field: 'frame_height_mode',
    default_severity: 'info',
    source_function: 'applyApplicationRules',
    source_line: 1643,
  },
  {
    rule_id: 'ar_custom_frame_info',
    human_name: 'Custom Frame Height Selected',
    check_description: 'Custom frame height is a cost option',
    category: 'frame',
    field: 'frame_height_mode',
    default_severity: 'info',
    source_function: 'applyApplicationRules',
    source_line: 1652,
  },
  {
    rule_id: 'ar_cleat_height_frame_contribution',
    human_name: 'Cleat Height Adds to Frame',
    check_description: 'Frame height includes 2x cleat height (carry + return)',
    category: 'frame',
    field: 'frame_height_mode',
    default_severity: 'info',
    source_function: 'applyApplicationRules',
    source_line: 1667,
  },
  {
    rule_id: 'ar_low_profile_cleats_error',
    human_name: 'Low Profile + Cleats Incompatible',
    check_description: 'Low Profile requires snub rollers but cleated belts cannot run on snubs',
    category: 'frame',
    field: 'frame_height_mode',
    default_severity: 'error',
    source_function: 'applyApplicationRules',
    source_line: 1682,
  },

  // --- Sprocket Warnings ---
  {
    rule_id: 'ar_chain_ratio_low',
    human_name: 'Chain Ratio Below 0.5',
    check_description: 'Chain ratio below 0.5 — unusual speed-up configuration',
    category: 'sprocket',
    field: 'gm_sprocket_teeth',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1705,
  },
  {
    rule_id: 'ar_chain_ratio_high',
    human_name: 'Chain Ratio Above 3.0',
    check_description: 'Chain ratio exceeds 3.0 — consider using a higher gearbox ratio',
    category: 'sprocket',
    field: 'drive_shaft_sprocket_teeth',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1712,
  },
  {
    rule_id: 'ar_gm_sprocket_small',
    human_name: 'GM Sprocket Below 12T',
    check_description: 'Gearmotor sprocket below 12T minimum — may cause accelerated wear',
    category: 'sprocket',
    field: 'gm_sprocket_teeth',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1722,
  },
  {
    rule_id: 'ar_drive_sprocket_small',
    human_name: 'Drive Shaft Sprocket Below 12T',
    check_description: 'Drive shaft sprocket below 12T minimum — may cause accelerated wear',
    category: 'sprocket',
    field: 'drive_shaft_sprocket_teeth',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1729,
  },

  // --- Speed Warnings ---
  {
    rule_id: 'ar_belt_speed_high',
    human_name: 'Belt Speed Exceeds 300 FPM',
    check_description: 'Belt speed > 300 FPM — verify this is intentional',
    category: 'speed',
    field: 'belt_speed_fpm',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1743,
  },
  {
    rule_id: 'ar_gear_ratio_low',
    human_name: 'Gear Ratio Below 5',
    check_description: 'Calculated gear ratio below 5 — may require special gearbox',
    category: 'drive',
    field: 'belt_speed_fpm',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1772,
  },
  {
    rule_id: 'ar_gear_ratio_high',
    human_name: 'Gear Ratio Above 60',
    check_description: 'Calculated gear ratio exceeds 60 — may require multiple reduction stages',
    category: 'drive',
    field: 'belt_speed_fpm',
    default_severity: 'warning',
    source_function: 'applyApplicationRules',
    source_line: 1780,
  },

  // --- Premium (belt only) ---
  {
    rule_id: 'ar_premium_feature',
    human_name: 'Premium Feature Flag',
    check_description: 'Configuration includes premium features (belt conveyor only)',
    category: 'premium',
    field: 'premium',
    default_severity: 'info',
    source_function: 'applyApplicationRules',
    source_line: 1796,
  },

  // =========================================================================
  // validateTob() — Commit-mode TOB validation
  // =========================================================================
  {
    rule_id: 'tob_tail_htob_required',
    human_name: 'Tail TOB Required (H_TOB Commit)',
    check_description: 'Tail TOB is required in H_TOB geometry mode when saving',
    category: 'support',
    field: 'tail_tob_in',
    default_severity: 'error',
    source_function: 'validateTob',
    source_line: 1843,
  },
  {
    rule_id: 'tob_drive_htob_required',
    human_name: 'Drive TOB Required (H_TOB Commit)',
    check_description: 'Drive TOB is required in H_TOB geometry mode when saving',
    category: 'support',
    field: 'drive_tob_in',
    default_severity: 'error',
    source_function: 'validateTob',
    source_line: 1849,
  },
  {
    rule_id: 'tob_tail_floor_required',
    human_name: 'Tail TOB Required (Floor, Commit)',
    check_description: 'Tail TOB is required when reference end is tail (commit mode)',
    category: 'support',
    field: 'tail_tob_in',
    default_severity: 'error',
    source_function: 'validateTob',
    source_line: 1862,
  },
  {
    rule_id: 'tob_drive_floor_required',
    human_name: 'Drive TOB Required (Floor, Commit)',
    check_description: 'Drive TOB is required when reference end is drive (commit mode)',
    category: 'support',
    field: 'drive_tob_in',
    default_severity: 'error',
    source_function: 'validateTob',
    source_line: 1870,
  },

  // =========================================================================
  // applyHeightWarnings() — Height and angle warnings
  // =========================================================================
  {
    rule_id: 'hw_adjustment_range_very_large',
    human_name: 'Very Large Adjustment Range',
    check_description: 'Adjustment range > 12" — verify leg feasibility',
    category: 'height',
    field: 'adjustment_required_in',
    default_severity: 'warning',
    source_function: 'applyHeightWarnings',
    source_line: 1896,
  },
  {
    rule_id: 'hw_adjustment_range_large',
    human_name: 'Large Adjustment Range',
    check_description: 'Adjustment range > 6" — may require special leg design',
    category: 'height',
    field: 'adjustment_required_in',
    default_severity: 'info',
    source_function: 'applyHeightWarnings',
    source_line: 1902,
  },
  {
    rule_id: 'hw_angle_mismatch',
    human_name: 'Angle Mismatch (TOB vs Incline)',
    check_description: 'Implied angle from TOB heights differs from entered incline by > 0.5°',
    category: 'height',
    field: 'conveyor_incline_deg',
    default_severity: 'warning',
    source_function: 'applyHeightWarnings',
    source_line: 1938,
  },

  // =========================================================================
  // applyPciOutputRules() — PCI tube stress validation
  // =========================================================================
  {
    rule_id: 'pci_tube_geometry_error',
    human_name: 'PCI: Invalid Tube Geometry',
    check_description: 'Tube geometry is invalid — cannot calculate stress',
    category: 'pci',
    field: 'drive_tube_od_in',
    default_severity: 'error',
    source_function: 'applyPciOutputRules',
    source_line: 2042,
  },
  {
    rule_id: 'pci_drive_stress_fail',
    human_name: 'PCI: Drive Tube Stress Exceeded (Enforce)',
    check_description: 'Drive pulley tube stress exceeds PCI limit (enforce mode)',
    category: 'pci',
    field: 'drive_tube_od_in',
    default_severity: 'error',
    source_function: 'applyPciOutputRules',
    source_line: 2052,
  },
  {
    rule_id: 'pci_tail_stress_fail',
    human_name: 'PCI: Tail Tube Stress Exceeded (Enforce)',
    check_description: 'Tail pulley tube stress exceeds PCI limit (enforce mode)',
    category: 'pci',
    field: 'tail_tube_od_in',
    default_severity: 'error',
    source_function: 'applyPciOutputRules',
    source_line: 2059,
  },
  {
    rule_id: 'pci_drive_stress_warn',
    human_name: 'PCI: Drive Tube Stress Warning',
    check_description: 'Drive pulley tube stress exceeds PCI limit — consider larger shell',
    category: 'pci',
    field: 'drive_tube_od_in',
    default_severity: 'warning',
    source_function: 'applyPciOutputRules',
    source_line: 2070,
  },
  {
    rule_id: 'pci_tail_stress_warn',
    human_name: 'PCI: Tail Tube Stress Warning',
    check_description: 'Tail pulley tube stress exceeds PCI limit — consider larger shell',
    category: 'pci',
    field: 'tail_tube_od_in',
    default_severity: 'warning',
    source_function: 'applyPciOutputRules',
    source_line: 2078,
  },
  {
    rule_id: 'pci_hub_centers_estimated',
    human_name: 'PCI: Hub Centers Estimated',
    check_description: 'Hub centers defaulted to belt width — provide actual hub centers for accuracy',
    category: 'pci',
    field: 'hub_centers_in',
    default_severity: 'info',
    source_function: 'applyPciOutputRules',
    source_line: 2088,
  },
  {
    rule_id: 'pci_status_estimated',
    human_name: 'PCI: Stress Check Passed (Estimated)',
    check_description: 'PCI tube stress check passed with estimated hub centers',
    category: 'pci',
    field: 'hub_centers_in',
    default_severity: 'info',
    source_function: 'applyPciOutputRules',
    source_line: 2097,
  },

  // =========================================================================
  // applyHubConnectionRules() — Hub connection warnings
  // =========================================================================
  {
    rule_id: 'hub_not_ideal_for_drive',
    human_name: 'Hub Type Not Ideal for Drive',
    check_description: 'ER internal bearings or dead shaft assembly is not ideal for drive pulleys',
    category: 'pci',
    field: 'drive_pulley_hub_connection_type',
    default_severity: 'warning',
    source_function: 'applyHubConnectionRules',
    source_line: 2135,
  },
  {
    rule_id: 'hub_drive_taper_lock',
    human_name: 'Drive Pulley Taper-Lock Warning',
    check_description: 'Taper-Lock not recommended for two-hub pulleys — prefer XT',
    category: 'pci',
    field: 'drive_pulley_bushing_system',
    default_severity: 'warning',
    source_function: 'applyHubConnectionRules',
    source_line: 2145,
  },
  {
    rule_id: 'hub_tail_taper_lock',
    human_name: 'Tail Pulley Taper-Lock Warning',
    check_description: 'Taper-Lock not recommended for two-hub pulleys — prefer XT',
    category: 'pci',
    field: 'tail_pulley_bushing_system',
    default_severity: 'warning',
    source_function: 'applyHubConnectionRules',
    source_line: 2153,
  },
];

/** Quick lookup by rule_id */
export const RULE_DEFINITIONS_MAP = new Map(
  RULE_DEFINITIONS.map((r) => [r.rule_id, r])
);

/** Total rule count */
export const TOTAL_RULE_COUNT = RULE_DEFINITIONS.length;
